In [1]:
@time include("setup.jl")

Total number of nodes on fault = 121
Average node spacing = 0.0004
dt = 0.00007477186690791
Setup Complete
  6.303571 seconds (2.70 M allocations: 141.573 MiB, 0.50% gc time)


In [ ]:
# Plot friction parameters
using Gadfly

fricPlot = plot(layer(x = (cca-ccb).*1e3 + 10, y = FltX,Theme(default_color=colorant"red"), Geom.point),
                layer(x = Seff/1e6, y = FltX, Theme(default_color=colorant"deepskyblue"), Geom.point),
                layer(x = tauo/1e6, y = FltX, Theme(default_color=colorant"green"), Geom.point),
                Guide.xlabel("Scaled (a-b)/ Stress value"),
                Guide.ylabel("Depth (m)"),
                Guide.title("Rate and state friction/Stress"),
                Coord.Cartesian(ymin=-24))

In [28]:
@time include("timesolver.jl")

  1.470192 seconds (2.25 M allocations: 442.644 MiB, 13.62% gc time)


121×10 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 ⋮                        ⋮                      
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0 

In [7]:
t1 = [0]
t2 = zeros(1e6);

In [8]:
function f1(t1)
    for i = 1:1e5
        t1 = push!(t1, i)
    end
end

function f2(t2)
    for i = 1:100000
        t2[i] = i
    end
    t2 = t2[1:100000]
end

f2 (generic function with 1 method)

In [22]:
@time f1(t1)

  0.001550 seconds (4 allocations: 160 bytes)


In [23]:
@time f2(t2);

  0.000532 seconds (6 allocations: 781.484 KiB)


In [24]:
d2 = reshape(collect(1:9), 3, 3)

3×3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [25]:
d2 = d2[:,1:2]

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6