<h1> Earthquake Cycle Simulations

In [ ]:
# Plot friction parameters
using Gadfly

fricPlot = plot(layer(x = (cca-ccb).*1e3 + 10, y = FltX/1e3,Theme(default_color=colorant"red"), Geom.point),
                layer(x = Seff/1e6, y = FltX/1e3, Theme(default_color=colorant"deepskyblue"), Geom.point),
                layer(x = tauo/1e6, y = FltX/1e3, Theme(default_color=colorant"green"), Geom.point),
                Guide.xlabel("Scaled (a-b)/ Stress value"),
                Guide.ylabel("Depth (m)"),
                Guide.title("Rate and state friction/Stress"),
                Coord.Cartesian(ymin=-24))

In [1]:
@time include("src/setup.jl")
@time include("src/timesolver.jl")

Total number of nodes on fault = 121
Average node spacing = 400.0
dt = 0.04486312014474891
Setup Complete
  8.045617 seconds (5.03 M allocations: 576.999 MiB, 1.55% gc time)

Simulation Complete
 19.762549 seconds (168.93 M allocations: 38.377 GiB, 7.07% gc time)


In [3]:
@time include("src/setup.jl")
include("src/PCG.jl")
include("src/dtevol.jl")
include("src/NRsearch.jl")
include("src/otherFunctions.jl")

temp = [0.0]

Total number of nodes on fault = 121
Average node spacing = 400.0
dt = 0.04486312014474891


Setup Complete
  2.159006 seconds (2.51 M allocations: 447.844 MiB, 4.51% gc time)


1-element Array{Float64,1}:
 0.0

In [3]:
 dPre = d[:]
        vPre = v[:]

        # Update
        d = d + dt*v + (half_dt^2)*a

        # Prediction
        v = v + half_dt*a
        a[:] = 0

0

In [25]:
global locall = zeros(5,5)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [26]:
# Internal forces -K*d[t+1] stored in global array 'a'
        for eo = 1:Nel
            
            # Switch to local element representation
            ig = iglob[:,:,eo]
            isETA = eo<=Nel_ETA
            if isETA
                locall = d[ig] + eta.*v[ig]
            else
                locall = d[ig]
            end
            # Gradients wrt local variables
            d_xi = Ht*locall
            d_eta = locall*H
        
            # Element contribution
            wloc = W[:,:,eo]
            d_xi = wloc.*d_xi
            d_xi = H*d_xi
            d_eta = wloc.*d_eta
            d_eta = d_eta*Ht
            locall = coefint1*d_xi + coefint2*d_eta

            # Assemble into global vector
            a[ig] = a[ig] - locall
        
        end

5×5 Array{Float64,2}:
  -139.736  -71517.7     -92985.7     -70974.1     -13108.6  
 70474.3        67.6643      75.2486      88.4307    -122.604
 91980.8       894.112      -43.4397     511.854     -152.818
 70594.5       438.812      485.364     -538.611      366.285
 13045.2       -49.5355     286.316      520.792     -196.941

In [2]:
eo = 1
ig = iglob[:,:,eo]
            isETA = eo<=Nel_ETA
            if isETA
                locall = d[ig] + eta.*v[ig]
            else
                locall = d[ig]
            end
            # Gradients wrt local variables
            d_xi = Ht*locall
            d_eta = locall*H
        
            # Element contribution
            wloc = W[:,:,eo]
            d_xi = wloc.*d_xi
            d_xi = H*d_xi
            d_eta = wloc.*d_eta
            d_eta = d_eta*Ht
            locall = coefint1*d_xi + coefint2*d_eta

            # Assemble into global vector
            a[ig] = a[ig] - locall

9801×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮  
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [7]:
wloc = W[:,:,eo]
            d_xi = wloc.*d_xi

5×5 Array{Float64,2}:
 0.0  -21.2991    56.7006   -27.26     2.16884
 0.0   88.7545   358.095    420.435   62.7979 
 0.0  321.512   1111.9     1261.48   258.956  
 0.0  342.956   1211.82    1454.66   352.887  
 0.0   85.7509   199.155    357.816   78.8734 

In [10]:
d_xi

5×5 Array{Float64,2}:
 0.0  -1.22107e-8  2.48876e-8  -1.56281e-8  6.76956e-9
 0.0   9.34579e-9  2.88696e-8   4.42716e-8  3.60018e-8
 0.0   2.59202e-8  6.86318e-8   1.01701e-7  1.13663e-7
 0.0   3.6113e-8   9.76965e-8   1.53175e-7  2.02309e-7
 0.0   4.91607e-8  8.74151e-8   2.05135e-7  2.46186e-7

In [13]:
Ht*locall

5×5 Array{Float64,2}:
 0.0  -1.22107e-8  2.48876e-8  -1.56281e-8  6.76956e-9
 0.0   9.34579e-9  2.88696e-8   4.42716e-8  3.60018e-8
 0.0   2.59202e-8  6.86318e-8   1.01701e-7  1.13663e-7
 0.0   3.6113e-8   9.76965e-8   1.53175e-7  2.02309e-7
 0.0   4.91607e-8  8.74151e-8   2.05135e-7  2.46186e-7

In [14]:
locall

5×5 Array{Float64,2}:
 0.0  9.28195e-6  2.68671e-5  4.44419e-5  5.37001e-5
 0.0  9.28182e-6  2.68758e-5  4.44477e-5  5.37072e-5
 0.0  9.29453e-6  2.69066e-5  4.4498e-5   5.3755e-5 
 0.0  9.31436e-6  2.69634e-5  4.45796e-5  5.38584e-5
 0.0  9.32883e-6  2.6996e-5   4.46407e-5  5.3936e-5 

In [15]:
Ht

5×5 Array{Float64,2}:
 -5.0       6.7565    -2.66667   1.41016   -0.5    
 -1.24099   0.0        1.74574  -0.763763   0.25901
  0.375    -1.33658    0.0       1.33658   -0.375  
 -0.25901   0.763763  -1.74574   0.0        1.24099
  0.5      -1.41016    2.66667  -6.7565     5.0    

In [17]:
aq1 = reshape(collect(1:9),3,3)
aq2 = reshape(collect(9:17),3,3)

3×3 Array{Int64,2}:
  9  12  15
 10  13  16
 11  14  17

In [18]:
aq1*aq2

3×3 Array{Int64,2}:
 126  162  198
 156  201  246
 186  240  294